import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1234",
    database="learnquest",
    charset="utf8"
)

cursor = db.cursor()

questions = [

# LEVEL 1 — ML BASICS
(21, "What is Machine Learning?",
 "పైథాన్‌లో మెషిన్ లెర్నింగ్ అంటే ఏమిటి?",
 "मशीन लर्निंग क्या है?",
 ["A system that learns patterns from data",
  "A system that only stores files",
  "A system that only performs calculations",
  "A system that only displays webpages"],
 ["డేటా నుండి నమూనాలను నేర్చుకునే వ్యవస్థ",
  "ఫైళ్లను మాత్రమే నిల్వ చేసే వ్యవస్థ",
  "లెక్కలు మాత్రమే చేసే వ్యవస్థ",
  "వెబ్‌పేజీలను మాత్రమే చూపించే వ్యవస్థ"],
 ["डेटा से पैटर्न सीखने वाली प्रणाली",
  "जो केवल फाइलें संग्रहीत करती है",
  "जो केवल गणना करती है",
  "जो केवल वेबपेज दिखाती है"], "A"),

(21, "What is training data?",
 "Training data అంటే ఏమిటి?",
 "Training data क्या होता है?",
 ["Data used to train a model",
  "Data used to shut down a model",
  "Data used to delete a model",
  "Data used to design a webpage"],
 ["మోడల్‌కు శిక్షణ ఇవ్వడానికి ఉపయోగించే డేటా",
  "మోడల్‌ను ఆపడానికి ఉపయోగించే డేటా",
  "మోడల్‌ను తొలగించడానికి ఉపయోగించే డేటా",
  "వెబ్‌పేజీ రూపొందించడానికి ఉపయోగించే డేటా"],
 ["मॉडल को प्रशिक्षित करने के लिए उपयोग किया जाने वाला डेटा",
  "मॉडल को बंद करने वाला डेटा",
  "मॉडल को हटाने वाला डेटा",
  "वेबपेज बनाने वाला डेटा"], "A"),

(21, "What is a feature in Machine Learning?",
 "Machine Learningలో feature అంటే ఏమిటి?",
 "Machine Learning में feature क्या है?",
 ["An input variable",
  "The final prediction",
  "The model name",
  "The computer name"],
 ["ఇన్‌పుట్ వేరియబుల్",
  "చివరి అంచనా",
  "మోడల్ పేరు",
  "కంప్యూటర్ పేరు"],
 ["इनपुट वेरिएबल",
  "अंतिम भविष्यवाणी",
  "मॉडल का नाम",
  "कंप्यूटर का नाम"], "A"),

(21, "What is a label?",
 "Machine Learningలో label అంటే ఏమిటి?",
 "Machine Learning में label क्या है?",
 ["The target output",
  "An input feature",
  "The dataset name",
  "The algorithm name"],
 ["టార్గెట్ అవుట్‌పుట్",
  "ఇన్‌పుట్ ఫీచర్",
  "డేటాసెట్ పేరు",
  "అల్గారిథమ్ పేరు"],
 ["टार्गेट आउटपुट",
  "इनपुट फीचर",
  "डेटासेट का नाम",
  "एल्गोरिथ्म का नाम"], "A"),

(21, "Why is data important in Machine Learning?",
 "Machine Learningలో data ఎందుకు ముఖ్యమైనది?",
 "Machine Learning में data महत्वपूर्ण क्यों है?",
 ["It helps the model learn patterns",
  "It deletes the model",
  "It removes every feature",
  "It replaces the computer"],
 ["ఇది మోడల్‌కు నమూనాలను నేర్చుకోవడంలో సహాయపడుతుంది",
  "ఇది మోడల్‌ను తొలగిస్తుంది",
  "ఇది అన్ని ఫీచర్లను తొలగిస్తుంది",
  "ఇది కంప్యూటర్‌ను భర్తీ చేస్తుంది"],
 ["यह मॉडल को पैटर्न सीखने में मदद करता है",
  "यह मॉडल को हटा देता है",
  "यह सभी फीचर हटा देता है",
  "यह कंप्यूटर की जगह लेता है"], "A"),

# LEVEL 2 — DATA & FEATURES
(22, "What is a dataset?",
 "Dataset అంటే ఏమిటి?",
 "Dataset क्या है?",
 ["A collection of data",
  "A programming language",
  "A computer monitor",
  "A single instruction"],
 ["డేటా యొక్క సమాహారం",
  "ఒక ప్రోగ్రామింగ్ భాష",
  "ఒక కంప్యూటర్ మానిటర్",
  "ఒక సూచన"],
 ["डेटा का संग्रह",
  "एक प्रोग्रामिंग भाषा",
  "एक कंप्यूटर मॉनिटर",
  "एक निर्देश"], "A"),

(22, "What is data preprocessing?",
 "Data preprocessing అంటే ఏమిటి?",
 "Data preprocessing क्या है?",
 ["Cleaning and preparing data",
  "Deleting the model",
  "Changing the computer",
  "Creating an operating system"],
 ["డేటాను శుభ్రపరచి సిద్ధం చేయడం",
  "మోడల్‌ను తొలగించడం",
  "కంప్యూటర్‌ను మార్చడం",
  "ఆపరేటింగ్ సిస్టమ్‌ను తయారు చేయడం"],
 ["डेटा को साफ और तैयार करना",
  "मॉडल को हटाना",
  "कंप्यूटर को बदलना",
  "ऑपरेटिंग सिस्टम बनाना"], "A"),

(22, "What is a missing value?",
 "Datasetలో missing value అంటే ఏమిటి?",
 "Dataset में missing value क्या है?",
 ["A value that is not present",
  "A duplicated value",
  "A predicted value",
  "A sorted value"],
 ["లేని విలువ",
  "డూప్లికేట్ విలువ",
  "అంచనా వేసిన విలువ",
  "క్రమబద్ధీకరించిన విలువ"],
 ["जो मान मौजूद नहीं है",
  "दोहराया गया मान",
  "भविष्यवाणी किया गया मान",
  "क्रमबद्ध मान"], "A"),

(22, "Why do we split data into training and testing sets?",
 "Dataను training మరియు testing setsగా ఎందుకు విభజిస్తాము?",
 "Data को training और testing sets में क्यों बाँटते हैं?",
 ["To evaluate the trained model",
  "To increase file size",
  "To remove all features",
  "To change the programming language"],
 ["శిక్షణ పొందిన మోడల్‌ను మూల్యాంకనం చేయడానికి",
  "ఫైల్ పరిమాణాన్ని పెంచడానికి",
  "అన్ని ఫీచర్లను తొలగించడానికి",
  "ప్రోగ్రామింగ్ భాషను మార్చడానికి"],
 ["प्रशिक्षित मॉडल का मूल्यांकन करने के लिए",
  "फाइल का आकार बढ़ाने के लिए",
  "सभी फीचर हटाने के लिए",
  "प्रोग्रामिंग भाषा बदलने के लिए"], "A"),

(22, "What is normalization used for?",
 "Normalization ఎందుకు ఉపయోగిస్తారు?",
 "Normalization का उपयोग क्यों किया जाता है?",
 ["To put feature values on a comparable scale",
  "To delete all rows",
  "To create a computer",
  "To remove the dataset"],
 ["ఫీచర్ విలువలను పోల్చదగిన స్కేల్‌లోకి తీసుకురావడానికి",
  "అన్ని వరుసలను తొలగించడానికి",
  "కంప్యూటర్‌ను తయారు చేయడానికి",
  "డేటాసెట్‌ను తొలగించడానికి"],
 ["फीचर मानों को तुलनीय पैमाने पर लाने के लिए",
  "सभी पंक्तियाँ हटाने के लिए",
  "कंप्यूटर बनाने के लिए",
  "डेटासेट हटाने के लिए"], "A"),

# LEVEL 3 — SUPERVISED LEARNING
(23, "What is supervised learning?",
 "Supervised learning అంటే ఏమిటి?",
 "Supervised learning क्या है?",
 ["Learning using labeled data",
  "Learning without any data",
  "Learning by deleting data",
  "Learning by changing hardware"],
 ["లేబుల్ చేసిన డేటాను ఉపయోగించి నేర్చుకోవడం",
  "డేటా లేకుండా నేర్చుకోవడం",
  "డేటాను తొలగించి నేర్చుకోవడం",
  "హార్డ్‌వేర్ మార్చి నేర్చుకోవడం"],
 ["लेबल किए गए डेटा का उपयोग करके सीखना",
  "बिना डेटा के सीखना",
  "डेटा हटाकर सीखना",
  "हार्डवेयर बदलकर सीखना"], "A"),

(23, "What is classification?",
 "Classification అంటే ఏమిటి?",
 "Classification क्या है?",
 ["Predicting a category",
  "Predicting only a continuous number",
  "Grouping without labels only",
  "Removing features"],
 ["ఒక కేటగిరీని అంచనా వేయడం",
  "నిరంతర సంఖ్యను మాత్రమే అంచనా వేయడం",
  "లేబుల్స్ లేకుండా మాత్రమే గ్రూప్ చేయడం",
  "ఫీచర్లను తొలగించడం"],
 ["किसी श्रेणी की भविष्यवाणी करना",
  "केवल निरंतर संख्या की भविष्यवाणी करना",
  "बिना लेबल के केवल समूह बनाना",
  "फीचर हटाना"], "A"),

(23, "What is regression?",
 "Regression అంటే ఏమిటి?",
 "Regression क्या है?",
 ["Predicting a continuous value",
  "Predicting only categories",
  "Deleting data",
  "Grouping images"],
 ["నిరంతర విలువను అంచనా వేయడం",
  "కేటగిరీలను మాత్రమే అంచనా వేయడం",
  "డేటాను తొలగించడం",
  "చిత్రాలను గ్రూప్ చేయడం"],
 ["एक निरंतर मान की भविष्यवाणी करना",
  "केवल श्रेणियों की भविष्यवाणी करना",
  "डेटा हटाना",
  "चित्रों को समूह बनाना"], "A"),

(23, "Which algorithm can be used for classification?",
 "Classification కోసం ఏ algorithm ఉపయోగించవచ్చు?",
 "Classification के लिए कौन सा algorithm उपयोग किया जा सकता है?",
 ["Decision Tree",
  "K-Means",
  "PCA",
  "Apriori"],
 ["Decision Tree",
  "K-Means",
  "PCA",
  "Apriori"], 
 ["Decision Tree",
  "K-Means",
  "PCA",
  "Apriori"], "A"),

(23, "What is overfitting?",
 "Overfitting అంటే ఏమిటి?",
 "Overfitting क्या है?",
 ["Good training performance but poor unseen-data performance",
  "No training data",
  "No features",
  "Only random predictions"],
 ["Training dataపై మంచి performance కానీ కొత్త dataపై చెడు performance",
  "Training data లేకపోవడం",
  "Features లేకపోవడం",
  "Random predictions మాత్రమే ఇవ్వడం"],
 ["Training data पर अच्छा लेकिन नए data पर खराब प्रदर्शन",
  "Training data का न होना",
  "Features का न होना",
  "केवल random predictions देना"], "A"),

# LEVEL 4 — UNSUPERVISED LEARNING
(24, "What is unsupervised learning?",
 "Unsupervised learning అంటే ఏమిటి?",
 "Unsupervised learning क्या है?",
 ["Learning without labeled target outputs",
  "Learning only with labels",
  "Learning by deleting data",
  "Learning without features"],
 ["లేబుల్స్ లేని డేటా నుండి నేర్చుకోవడం",
  "లేబుల్స్‌తో మాత్రమే నేర్చుకోవడం",
  "డేటాను తొలగించి నేర్చుకోవడం",
  "ఫీచర్లు లేకుండా నేర్చుకోవడం"],
 ["बिना लेबल वाले target outputs के सीखना",
  "केवल labels के साथ सीखना",
  "डेटा हटाकर सीखना",
  "बिना features के सीखना"], "A"),

(24, "What is clustering?",
 "Clustering అంటే ఏమిటి?",
 "Clustering क्या है?",
 ["Grouping similar data points",
  "Predicting a known label",
  "Calculating passwords",
  "Compiling source code"],
 ["సారూప్యమైన డేటా పాయింట్లను సమూహాలుగా విభజించడం",
  "తెలిసిన లేబుల్‌ను అంచనా వేయడం",
  "పాస్‌వర్డ్‌లను లెక్కించడం",
  "సోర్స్ కోడ్‌ను కంపైల్ చేయడం"],
 ["समान डेटा बिंदुओं को समूहों में बाँटना",
  "ज्ञात label की भविष्यवाणी करना",
  "पासवर्ड की गणना करना",
  "source code compile करना"], "A"),

(24, "Which algorithm is commonly used for clustering?",
 "Clustering కోసం సాధారణంగా ఏ algorithm ఉపయోగిస్తారు?",
 "Clustering के लिए सामान्यतः कौन सा algorithm उपयोग किया जाता है?",
 ["K-Means",
  "Linear Regression",
  "Logistic Regression",
  "Decision Tree"],
 ["K-Means",
  "Linear Regression",
  "Logistic Regression",
  "Decision Tree"],
 ["K-Means",
  "Linear Regression",
  "Logistic Regression",
  "Decision Tree"], "A"),

(24, "What is dimensionality reduction?",
 "Dimensionality reduction అంటే ఏమిటి?",
 "Dimensionality reduction क्या है?",
 ["Reducing the number of features",
  "Increasing the number of labels",
  "Duplicating every row",
  "Deleting the computer"],
 ["ఫీచర్ల సంఖ్యను తగ్గించడం",
  "లేబుల్స్ సంఖ్యను పెంచడం",
  "ప్రతి వరుసను డూప్లికేట్ చేయడం",
  "కంప్యూటర్‌ను తొలగించడం"],
 ["फीचर की संख्या कम करना",
  "Labels की संख्या बढ़ाना",
  "हर row को duplicate करना",
  "कंप्यूटर हटाना"], "A"),

(24, "What is PCA commonly used for?",
 "PCA సాధారణంగా దేనికి ఉపయోగిస్తారు?",
 "PCA का सामान्य उपयोग क्या है?",
 ["Dimensionality reduction",
  "Password generation",
  "Webpage creation",
  "Database deletion"],
 ["Dimensionality reduction",
  "Password generation",
  "Webpage creation",
  "Database deletion"],
 ["Dimensionality reduction",
  "Password generation",
  "Webpage creation",
  "Database deletion"], "A"),

# LEVEL 5 — MODEL EVALUATION
(25, "What is accuracy?",
 "Accuracy అంటే ఏమిటి?",
 "Accuracy क्या है?",
 ["Proportion of correct predictions",
  "Number of features",
  "Training time only",
  "Number of hidden layers"],
 ["సరైన అంచనాల నిష్పత్తి",
  "ఫీచర్ల సంఖ్య",
  "శిక్షణ సమయం మాత్రమే",
  "హిడెన్ లేయర్ల సంఖ్య"],
 ["सही predictions का अनुपात",
  "Features की संख्या",
  "केवल training time",
  "Hidden layers की संख्या"], "A"),

(25, "What is precision?",
 "Precision అంటే ఏమిటి?",
 "Precision क्या है?",
 ["Correct positive predictions among all positive predictions",
  "Correct predictions among all samples",
  "Negative predictions among all samples",
  "Training samples among test samples"],
 ["అన్ని positive predictionsలో సరైన positive predictions",
  "అన్ని samplesలో సరైన predictions",
  "అన్ని samplesలో negative predictions",
  "Test samplesలో training samples"],
 ["सभी positive predictions में सही positive predictions",
  "सभी samples में सही predictions",
  "सभी samples में negative predictions",
  "Test samples में training samples"], "A"),

(25, "What is recall?",
 "Recall అంటే ఏమిటి?",
 "Recall क्या है?",
 ["Correct positive predictions among all actual positives",
  "Correct predictions among all predictions",
  "Negative predictions among all positives",
  "Training samples among all features"],
 ["అన్ని actual positivesలో సరైన positive predictions",
  "అన్ని predictionsలో సరైన predictions",
  "అన్ని positivesలో negative predictions",
  "అన్ని featuresలో training samples"],
 ["सभी actual positives में सही positive predictions",
  "सभी predictions में सही predictions",
  "सभी positives में negative predictions",
  "सभी features में training samples"], "A"),

(25, "What is a confusion matrix?",
 "Confusion matrix అంటే ఏమిటి?",
 "Confusion matrix क्या है?",
 ["Counts of predicted and actual classes",
  "Only training time",
  "Only number of features",
  "Only dataset size"],
 ["Predicted మరియు actual classes సంఖ్యలను చూపిస్తుంది",
  "Training time మాత్రమే చూపిస్తుంది",
  "Features సంఖ్య మాత్రమే చూపిస్తుంది",
  "Dataset size మాత్రమే చూపిస్తుంది"],
 ["Predicted और actual classes की संख्या दिखाता है",
  "केवल training time दिखाता है",
  "केवल features की संख्या दिखाता है",
  "केवल dataset size दिखाता है"], "A"),

(25, "Why do we evaluate a Machine Learning model?",
 "Machine Learning modelను ఎందుకు evaluate చేస్తాము?",
 "Machine Learning model का evaluation क्यों करते हैं?",
 ["To understand how well the model performs",
  "To increase keyboard size",
  "To delete files",
  "To change the monitor"],
 ["మోడల్ ఎంత బాగా పనిచేస్తుందో తెలుసుకోవడానికి",
  "కీబోర్డ్ పరిమాణాన్ని పెంచడానికి",
  "ఫైళ్లను తొలగించడానికి",
  "మానిటర్‌ను మార్చడానికి"],
 ["यह समझने के लिए कि मॉडल कितना अच्छा प्रदर्शन करता है",
  "कीबोर्ड का आकार बढ़ाने के लिए",
  "फाइलें हटाने के लिए",
  "मॉनिटर बदलने के लिए"], "A")
]

query = """
INSERT INTO quizzes (
    level_id,
    question_en,
    question_te,
    question_hi,
    option_a_en,
    option_b_en,
    option_c_en,
    option_d_en,
    option_a_te,
    option_b_te,
    option_c_te,
    option_d_te,
    option_a_hi,
    option_b_hi,
    option_c_hi,
    option_d_hi,
    correct_answer,
    xp_reward
)
VALUES (
    %s,%s,%s,%s,
    %s,%s,%s,%s,
    %s,%s,%s,%s,
    %s,%s,%s,%s,
    %s,20
)
"""

for q in questions:

    level_id = q[0]
    question_en = q[1]
    question_te = q[2]
    question_hi = q[3]

    en = q[4]
    te = q[5]
    hi = q[6]
    correct = q[7]

    cursor.execute(
        query,
        (
            level_id,
            question_en,
            question_te,
            question_hi,

            en[0], en[1], en[2], en[3],

            te[0], te[1], te[2], te[3],

            hi[0], hi[1], hi[2], hi[3],

            correct
        )
    )

db.commit()

print("Machine Learning quiz questions added successfully!")
print("New questions inserted:", len(questions))

cursor.close()
db.close()